version: "2"
services: 
  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
     - "8000:8000"
     - "9000:9000"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./volumes/portainer/data:/data
    restart: unless-stopped
  influx:
    container_name: influx
    image: influxdb
    ports:
     - "8083:8083"
     - "8086:8086"
    environment:
     - INFLUXDB_USER=user
     - INFLUXDB_PASS=pass
     - INFLUXDB_NAME=dbname
     - PRE_CREATE_DB="dbname"
    volumes:
     - ./volumes/influxdb:/var/lib/influxdb
     - ./volumes/influxdb_backup:/var/lib/influxdb/backup
    restart: unless-stopped
  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
     - INFLUXDB_USER=user
     - INFLUXDB_PASS=pass
     - INFLUXDB_NAME=dbname
    ports:
     - "3000:3000"
    volumes:
     - ./volumes/grafana/data:/var/lib/grafana
     - ./volumes/grafana/log:/var/log/grafana
    links:
     - influx
    depends_on:
     - influx
    restart: unless-stopped
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
     - "1883:1883"
     - "9001:9001"
    volumes:
     - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
     - ./volumes/mosquitto/data:/mosquitto/data
     - ./volumes/mosquitto/log:/mosquitto/log
    restart: unless-stopped
  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
     - "1880:1880"
    volumes:
     - ./volumes/nodered:/data
    restart: unless-stopped
  telegraf:
    container_name: telegraf
    image: telegraf
    volumes:
     - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
     - influx
    restart: unless-stopped